django_practice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("to_do.urls", namespace="to_do")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

to_do/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    TaskListView,
    task_change_status, TagListView, TagUpdateView, TagDeleteView, TagCreateView, TaskDeleteView, TaskUpdateView,
    TaskCreateView,
)


class TegCreateView:
    pass


urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/manage/<int:pk>/<action>", task_change_status, name="task_change_status"),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("/create/", TaskCreateView.as_view(), name="to_do-create"),
    path("/<int:pk>/update/", TaskUpdateView.as_view(), name="to_do-update"),
    path("/<int:pk>/delete/", TaskDeleteView.as_view(), name="to_do-delete"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "to_do"

to_do/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    create = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField()
    tag = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["deadline"]

    def __str__(self):
        return f"{self.content} {self.create} {self.deadline} {self.status}"

to_do/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from to_do.models import Task, Tag


def task_change_status(request, pk, action):
    task = Task.objects.get(pk=pk)

    if action == "success":
        task.status = True
    if action == "undo":
        task.status = False

    task.save()

    return HttpResponseRedirect(reverse("to_do:index"))


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "to_do/index.html"
    paginate_by = 10
    ordering = ["status", "-create"]
    queryset = Task.objects.all().prefetch_related("tag")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")
    template_name = "to_do/task_confirm_delete.html"


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    paginate_by = 10


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "to_do/tag_confirm_delete.html"
    success_url = reverse_lazy("to_do:tag_list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>To Do</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}


        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
    <li class="list-group-item"><a href="{% url 'to_do:index' %}">Home</a></li>
    <li class="list-group-item"><a href="{% url 'to_do:tag_list' %}">Tags</a></li>
</ul>

templates/to_do/index.html
{% extends "base.html" %}

{% block content %}
    <h1 >TODO list
        <a style="float: right" class="btn btn-primary" href="" >Add task</a>
    </h1>

    <br>

    {% for task in task_list %}
        <p>
            <h3>{{ task.content }}
                {% if task.status %}
                    <span style="color: green">Done</span>
                    <a style="float: right" href="{% url 'to_do:task_change_status' pk=task.id action='undo' %}" class="btn btn-danger float-right-button">Undo</a>
                {% else %}
                    <span style="color: red">Not done</span>
                    <a style="float: right" href="{% url 'to_do:task_change_status' pk=task.id action='success' %}" class="btn btn-success float-right-button">Complete</a>
                {% endif %}
            </h3>
        </p>

        <p>Created: {{ task.create }}
            {% if task.deadline %}
                Deadline: {{ task.deadline }}
            {% endif %}
        </p>

        <p>Tags:
            {% for tag in task.tag.all %}
                {{ tag.name }}
            {% endfor %}
            <a href=""
               class="manage-task-tags">Update</a>
            <a href=""
               class="manage-task-tags">Delete</a>
        </p>


    {% endfor %}

{% endblock %}

templates/to_do/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Tag</h1>

    <p>You want to delete: {{ tag.name }}</p>
    <form method="POST" action="">
        {% csrf_token %}

        <input type="submit" value="Yes">
    </form>

{% endblock %}

templates/to_do/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1 >Tags
        <a class="btn btn-primary float-right" href="" >Add</a>
    </h1>

    <br>
    <table class="table">
        <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
        {% for tag in tag_list %}
            <p>
              <tr>
                <h3><td>{{ tag.name }}</td></h3>
                <td><a href=""
                   class="manage-task-tags">Update</a></td>
                <td><a href="{% url 'to_do:tag-delete' pk=tag.id %}"
                   class="manage-task-tags">Delete</a></td>
              </tr>
            </p>
        </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/to_do/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Task</h1>

    <p>You want to delete: {{ task.name }}</p>
    <form method="POST" action="">
        {% csrf_token %}

        <input type="submit" value="Yes">
    </form>

{% endblock %}

templates/to_do/update_tag.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Tag</h1>

    <form method="post" action="" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>

{% endblock %}

templates/to_do/update_task.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object|yesno:"Update, Create" }} Task</h1>

    <form method="post" action="" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit">
    </form>

{% endblock %}